---
title: torrez.org
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    is_page: true
- scope:
    path: ''
    type: posts
  values:
    layout: post
    is_post: true
cachebust: 20170307
description: A weblog by Andre Torrez.
author: Andre Torrez
baseurl: 
url: http://torrez.org
permalink: "/:year/:month/:title/"
twitter_username: torrez
twitter_blog_username: andre_torrez
github_username: torrez
email_address: andre@torrez.org
exclude:
- _site
- Gruntfile.js
- node_modules
- package.json
- README.md
- ".deploy"
- ".git"
- ".grunt"
- ".sass-cache"
- ".tmp"
kramdown:
  input: GFM
plugins:
- jekyll-sitemap
- jekyll-feed
